image:
  file: .gitpod.dockerfile
ports:
    - port: 3000
      onOpen: open-preview
    - port: 3306
      onOpen: ignore
tasks:
    - init: >
        cp .env.example .env;
        npm i -g heroku;
        pipenv install;
        psql -U gitpod -c 'CREATE DATABASE pokerswap;';
        psql -U gitpod -c 'CREATE EXTENSION unaccent;' -d pokerswap;
      command:
        pipenv install;
        pipenv run upgrade;
        pipenv run start;
